---
title: Parole più usate dai politici italiani su Twitter nelle scorse 24 ore
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: readable
---

<style>

</style>

```{r setup, include=FALSE}

library(flexdashboard)
library(rtweet)
library(tidyverse)
library(lubridate)
library(htmltools)
library(tidytext)
library(htmlwidgets)
library(tm)
library(devtools)
Sys.unsetenv("GITHUB_PAT")
devtools::install_git("https://github.com/Lchiffon/wordcloud2", upgrade = "always", force = TRUE)
library(wordcloud2)


api_key <- "C2skGJJmzQCzNBZ3CjVE2COXG"
api_secret_key <- "amYWEq8BmiqWMoEUHzMO1Bz8HTzPVeVOSmHc4xqO7LeFqsdGTs"
access_token <- "1174663297024569344-iDi5HqnUxqDfahA7hxlUIhNhZS4D25"
access_token_secret <- "B7FHSKQwF0uXnLTnMyUYVtigVWY6VC0lB0O3stsK9NC3p"

## authenticate via token
api_key <- Sys.getenv("API_KEY")
api_secret_key <-Sys.getenv("API_SECRET_KEY")
access_token <-Sys.getenv("ACCESS_TOKEN")
access_token_secret <- Sys.getenv("ACCESS_TOKEN_SECRET")
bearer_tokenm = Sys.getenv("BEARER_TOKEN")


app <- rtweet_app(bearer_token = "AAAAAAAAAAAAAAAAAAAAAHsDcQEAAAAAuNzK3xA%2BAuBfHHHAnUfjPV%2BVmS8%3D3ca3jr2qKfCFQOm8toDFxP5tXZtNf4XNBzf370trIXqrwwMqlx")
auth_as(app)

parlamento=read_csv("parlamento.csv") %>% 
    drop_na(Twitter)
parltweet=get_timeline(parlamento$Twitter, n=50, token = tokenb, check = FALSE)
parltweet=filter(parltweet, created_at>=(Sys.time() - 86400)) %>% 
 # filter(is_retweet==FALSE) %>% 
  filter(is_quote==FALSE)
flexdashboard::flex_dashboard()

partiticol=c("Lega"='green',
             "PD"='red',
             "Italia Viva"='#ca2c92',
             "M5S"='#ffea00', 
             "Ex M5S"='#c1c400', 
             "Forza Italia"='blue',
             "Coraggio Italia"='#600080',
             "CD"='gray',
             "MAIE"='darkblue',
             "Azione-+Europa"='#003399',
             "Verdi"='#008f39',
             "FDI"="#0d0099",
             "LEU"="darkred",
             "Noi con l’Italia"="gold2",
             "SVP"="black",
             "Senatore a vita"="grey",
             "UDC"="skyblue"
             )

write_as_csv(parltweet, file_name = paste(today("CEST"),".csv"))


df <- merge(parltweet, parlamento, by.x = "screen_name", by.y = "Twitter")
df$text <- as.character(df$text)
df$text=tolower(df$text)
df$text=gsub("\\s?(f|ht)(tp)(s?)(://)([^\\.]*)[\\.|/](\\S*)", "", df$text)
df$text <- gsub("\\$", "", df$text) 
df$text <- gsub("@\\w+", "", df$text)
df$text <- gsub("http\\w+", "", df$text)
df$text <- gsub("[[:punct:]]"," ", df$text)
df$text <- gsub('\\b [0-9]*[0-9]', '', df$text)
df$text <- gsub('^[0-9]*[0-9]', '', df$text)
df$text <- gsub('-', ' ', df$text)
df$text <- gsub('#', ' ', df$text)
df$text=gsub(" *\\b[[:alpha:]]{1}\\b *", " ", df$text)
  
unique(df$Partito)


itastop=as_tibble_col(stopwords("italian"), column_name = "word")

tokens <- df %>% 
  group_by(Partito) %>% 
  unnest_tokens(word, text) %>%
  group_by(Partito) %>% 
  count(word, sort = TRUE) %>% 
  anti_join(itastop) %>% 
  filter(n > 1) %>% 
  ungroup()

tokens
a= tokens %>% 
  slice_max(order_by = n, n=15) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(x = word, y = n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  labs(y = "Count",
       x = "Unique words",
       title = "Count of unique words found in tweets",
       subtitle = "Stop words removed from the list")
a

partiti=unique(na.omit(tokens$Partito))

for (i in partiti){
  outputfile <- paste(i,"output.html", sep="-")
  colore=partiticol[[i]]
  assign(as.character(i),value = filter(tokens,Partito==i) %>% 
           ungroup() %>% 
           select(word,n) %>% 
           wordcloud2(color = colore, size=0.5 ) )%>% 
  saveWidget(outputfile,selfcontained = FALSE)
  }
```

Row
-----------------------------------------------------------------------

### Lega Salvini Premier

```{r}
try(Lega, silent = TRUE)
```


### Fratelli d'Italia
```{r}
try(FDI, silent = TRUE)
```


### Partito Democratico
```{r}
try(PD, silent = TRUE)
```



Row
-----------------------------------------------------------------------

### Movimento 5 Stelle

```{r}
try(M5S, silent = TRUE)
```

### Forza Italia

```{r}
try(`Forza Italia`, silent = TRUE)
```


### Italia Viva
```{r}
try(`Italia Viva`, silent = TRUE)
```



Row
-----------------------------------------------------------------------

### Liberi e Uguali

```{r}
try(LEU, silent = TRUE)
```


### Azione-+Europa

```{r}
try(`Azione-+Europa`, silent = TRUE)
```


### Ex Movimento 5 Stelle

```{r}
try(`Ex M5S`, silent = TRUE)
```

